import "./load-env";
import { migrate } from "drizzle-orm/neon-http/migrator";
import { db } from "@/server/db/client";

/** Applies pending SQL migrations from ./drizzle (generated by `npm run db:generate`). */
async function run() {
  await migrate(db, { migrationsFolder: "drizzle" });
  console.log("Database schema is up to date.");
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
